name: Create Release Candidate

on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version
        required: true
        type: string

jobs:
  create-branch:
    name: Create release branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - uses: fregante/setup-git-user@v1
      - run: git checkout -b release/${{ github.event.inputs.version }}
      - run: git push origin release/${{ github.event.inputs.version }}

  bump-and-tag-release:
    name: Bump release version and push tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: release/${{ github.event.inputs.version }}
          token: ${{ secrets.PAT }}
      - uses: fregante/setup-git-user@v1
      - run: npm version --no-commit-hooks prerelease --preid rc -m "Upgrade release to v%s"
      - run: git push --follow-tags

  bump-and-tag-develop:
    name: Bump develop version and push tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
          token: ${{ secrets.PAT }}
      - uses: fregante/setup-git-user@v1
      - run: npm version ${{ github.event.inputs.version }}-rc.0 --no-git-tag-version
      - run: npm version --no-commit-hooks --force preminor --preid beta -m "Upgrade develop to v%s [skip ci]"
      - run: git push --follow-tags
