name: Deploy Staging Environment

on:
  push:
    tags:
      - "v*.*.*-rc.*"

jobs:
  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy has been successfully finished"
