name: Lint, Build, Test

on:
  pull_request_target:
    branches:
      - development

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - run: echo "Lint has been successfully passed"

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build has been successfully passed"

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test has been successfully passed"
