name: Tag Release

on:
  pull_request:
    branches: ["release/**"]
    types: [closed]

jobs:
  bump-and-tag:
    name: Bump version and push tag
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - uses: fregante/setup-git-user@v1
      - run: npm version --no-commit-hooks prerelease --preid rc -m "Upgrade release to v%s"
      - run: git push --follow-tags
